# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: CommonUtils CICD

on:
  push:
    branches:
      - staging
    paths:
      - "CommonUtils/**"
      - ".github/workflows/commonutils.yml"

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'corretto'
        cache: maven
        server-id: GithubPackages # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Run tests and publish package
      run: |-
        cd CommonUtils
        mvn -B test --file pom.xml -s $GITHUB_WORKSPACE/settings.xml
        mvn --batch-mode deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}